# Generated by Django 3.2.13 on 2022-05-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author'),
        ),
    ]
